# yaml文件内容加密，正式则使用启动参数传入，-Djasypt.encryptor.password=tNFwPPxxv6#+&SlB
jasypt:
  encryptor:
    password: tNFwPPxxv6#+&SlB

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meteor?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      database: 11
      host: 127.0.0.1
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 系统配置
meteor:
  # 云存储类型
  oss:
    type: huawei
    endpoint:
    bucket:
    ak:
    sk:

# 微信相关配置
wx:
  # 小程序配置
  miniapp:
    #微信小程序的appid
    appid: 123456
    #微信小程序的Secret
    secret: abcdefg